language: python
python: "3.7"
dist: xenial

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present

cache:
  paths:
    - .venv

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - poetry config settings.virtualenvs.in-project true
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      script:
        - make test
    - stage: deploy
      script:
        - echo Deploying to PyPI...

before_deploy:
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
  - poetry build -f sdist

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
    tags: true
